### PR TITLE
Restore building for all of GHC 8.0 - 9.12

### LINKED ISSUE #32: 0.19 doesn't build with GHC 9.2
```[3 of 9] Compiling Data.VectorSpace ( src/Data/VectorSpace.hs, dist/build/Data/VectorSpace.dyn_o )

src/Data/VectorSpace.hs:222:10: error:
    Variable not in scope:
      liftA2
        :: (Scalar v1 -> v1 -> v1) -> (a -> Scalar v) -> (a -> v) -> a -> v
    |
222 |   (*^) = liftA2 (*^)
    |          ^^^^^^

src/Data/VectorSpace.hs:225:11: error:
    Variable not in scope:
      liftA2
        :: (v0 -> v0 -> Scalar v0) -> (a -> v) -> (a -> v) -> a -> Scalar v
    |
225 |   (<.>) = liftA2 (<.>)
    |           ^^^^^^
```

### PR DESCRIPTION
**Pull request by andreasabel**
Commits:

- **Delete trailing whitespace**
  

- **Fix conditionals for importing liftA2**
  

- **Require base >= 4.9 (GHC 8 and up)**
  

- **Add Haskell CI for GHC 8.0 - 9.12**

- Delete conditionals that are no longer needed for GHC 8 and up.

The CI provides the evidence that building works for all of GHC 8 and 9.
CI for older GHCs is no longer feasible, so it seems natural to drop GHC 7 and below.

CI ran successful at: https://github.com/andreasabel/vector-space/pull/1
  
Closes #32.
- #32

### CODE REVIEW

**Comment by conal** [comment]
Thanks, @andreasabel!
