### ISSUE TITLE
0.19 doesn't build with GHC 9.2

### ISSUE THREAD

**Issue by felixonmars** [conal/vector-space#32]
```[3 of 9] Compiling Data.VectorSpace ( src/Data/VectorSpace.hs, dist/build/Data/VectorSpace.dyn_o )

src/Data/VectorSpace.hs:222:10: error:
    Variable not in scope:
      liftA2
        :: (Scalar v1 -> v1 -> v1) -> (a -> Scalar v) -> (a -> v) -> a -> v
    |
222 |   (*^) = liftA2 (*^)
    |          ^^^^^^

src/Data/VectorSpace.hs:225:11: error:
    Variable not in scope:
      liftA2
        :: (v0 -> v0 -> Scalar v0) -> (a -> v) -> (a -> v) -> a -> Scalar v
    |
225 |   (<.>) = liftA2 (<.>)
    |           ^^^^^^
```

**Comment by conal** [comment]
Please see issue #30. Perhaps you and [rsoeldner](https://github.com/rsoeldner) could come up with a PR that works for GHC 9.2 through 9.10.

**Comment by conal** [comment]
Thank you for the report, and apologies about the breakage!

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a revision: https://hackage.haskell.org/package/vector-space-0.19/revisions/
I guess it's fine for now: users of older GHCs can stick to older releases. It would be nice to bump a lower bound to `base-4.18` in the repo though.

FWIW the migration guide for `liftA2` issues is available at https://github.com/haskell/core-libraries-committee/blob/main/guides/export-lifta2-prelude.md

**Comment by andreasabel** [comment]
> Please see issue [#30](https://github.com/conal/vector-space/pull/30). Perhaps you and [rsoeldner](https://github.com/rsoeldner) could come up with a PR that works for GHC 9.2 through 9.10.

I give it a shot.
